# credit: https://packaging.python.org/guides/supporting-windows-using-appveyor/

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "py36-x64"
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "py37-x64"

install:
  - "%PYTHON%\\python.exe setup.py install"

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py validate"

on_success:
  - "%PYTHON%\\python.exe codecov -e win-%PYTHON_VERSION%"